version: "3.9"

services:
  ticket-app-postgres:
    image: postgres:15.4
    container_name: ticket-app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      TZ: Asia/Tokyo
    ports:
      - "55440:5432"
    volumes:
      - ./docker//postgresql/data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
